### ISSUE TITLE
doesn't apear to be in the monodevelop add-ins galary 

### ISSUE THREAD

**Issue by se5a** [mrward/monodevelop-nuget-extensions#14]
MonoDevelop 5.10
I checked the monodevelop add-ins repository(alpha channel) but no luck there.
ended up finding it here: http://addins.monodevelop.com/Project/Index/121
and installing from file.

**Comment by mrward** [comment]
Seems OK for me with MonoDevelop 5.10.

<img width="782" alt="screen shot 2016-12-18 at 12 07 07" src="https://cloud.githubusercontent.com/assets/372361/21293381/a762c428-c51a-11e6-999d-f9bddce7a4df.png">

This is using Xamarin Studio 5.10 on the Mac. The url being used was http://addins.monodevelop.com/Alpha/Mac/5.10.3/main.mrep

I also tried the following urls which also returned the NuGet extensions addin:

http://addins.monodevelop.com/Alpha/Mac/5.0/main.mrep
http://addins.monodevelop.com/Alpha/Linux/5.0/main.mrep

I normally click the Refresh button to make sure the addin information is downloaded from the repository.

I can also see the NuGet extensions has been downloaded and installed. There were some downloads from yesterday recorded on the stats page I see on addins.monodevelop.com. So it looks OK to me.

**Comment by se5a** [comment]
Odd, I'm seeing it there now. yeah maybe I hadn't refreshed properly.
