### ISSUE TITLE
0.12 doesn't work latest 6.2 Beta

### ISSUE THREAD

**Issue by dhaligas** [mrward/monodevelop-nuget-extensions#15]
@mrward it appears release 0.12 doesn't work in 6.2 beta.  I click on the Manage Packages and nothing shows up

**Comment by mrward** [comment]
For 6.2 you need the as yet unpublished addin which is only available from GitHub:

https://github.com/mrward/monodevelop-addins/blob/gh-pages/6.2/MonoDevelop.PackageManagement.Extensions_0.12.mpack

The NuGet version in 6.2 changed to NuGet 3.5 which broke the addin that is published for 6.1.

**Comment by dhaligas** [comment]
Ok. I tried that version because I was running alpha. Which worked and I
updated to the RC release from yesterday and it doesn't

**Comment by mrward** [comment]
Looks to me as though currently alpha channel is the same as the beta channel.

I did have a similar problem to you switching between 6.1 and 6.2 and vice versa. I would try uninstalling the addin, restart Xamarin Studio, then install the addin again, and restart Xamarin Studio again so the menus are added.

Right now I have Xamarin Studio 6.2 (build 1718) installed and the Manage Packages dialog is working for me.

**Comment by dhaligas** [comment]
@mrward that did it.  thanks.  I will close this issue. btw this is the best addin for XS
