### ISSUE TITLE
Doesn't work with Beta 15.3

### ISSUE THREAD

**Issue by jimbobbennett** [mrward/monodevelop-nuget-extensions#18]
As the title really - if this is installed in the latest beta (15.3) then selecting the options from the menu doesn't do anything, the dialog doesn't popup.

**Comment by mrward** [comment]
Visual Studio Mac 7.1 from the beta channel has an updated the version of NuGet it uses. Everytime NuGet updates the NuGet extensions addin breaks.

The NuGet extensions addin 0.12.3 below works with Visual Studio for Mac 7.1:

https://github.com/mrward/monodevelop-addins/blob/gh-pages/7.1/MonoDevelop.PackageManagement.Extensions_0.12.3.mpack
