### ISSUE TITLE
Compatibility with Visual Studio for Mac 7.1 (Build 1297)

### ISSUE THREAD

**Issue by brianjquinn** [mrward/monodevelop-nuget-extensions#20]
The current plugin says it supports Visual Studio for Mac 7.0 (Build 2740) and does in fact not work with Visual Studio for Mac 7.1 (Build 1297). I was curious if there any plans to update the compatibility with the latest visual studio for mac build?

**Comment by mrward** [comment]
Every time NuGet updates in Visual Studio for Mac it breaks the NuGet extensions addin.

For VS Mac 7.1 you need [NuGet extensions 0.12.3](https://github.com/mrward/monodevelop-addins/blob/gh-pages/7.1/MonoDevelop.PackageManagement.Extensions_0.12.3.mpack).
