### ISSUE TITLE
0.12.4 does not seem to work in latest 7.2 Preview (build 617)

### ISSUE THREAD

**Issue by micdah** [mrward/monodevelop-nuget-extensions#21]
After upgrading to latest alpha release 7.2 Preview build 617, this extension seems to have stopped working.

Activating "Manage NuGet Packages..." (either from context menu or via Project menu) does not activate the window - in fact nothing seems to happen.

**Comment by mrward** [comment]
In VS Mac 7.2.0.617, which was released today, the NuGet addin was updated to use NuGet 4.3.1.4445. I have not yet re-built against the VS Mac 7.2.0.617 binaries and released a new version.

**Comment by mrward** [comment]
NuGet extensions 0.12.5 should work with VS Mac 7.2.0.617:

https://github.com/mrward/monodevelop-addins/blob/gh-pages/7.2/MonoDevelop.PackageManagement.Extensions_0.12.5.mpack

**Comment by micdah** [comment]
That is awesome, just updated - works flawlessy! 👍
