### ISSUE TITLE
ERROR VTable setup of type MonoDevelop.PackageManagement.ConsoleHostMSBuildNuGetProject failed

### ISSUE THREAD

**Issue by wenyonk** [mrward/monodevelop-nuget-extensions#23]
Just upgraded to latest VS for Mac 7.3 build 797

In Package Console Extension windows if am getting the following error:
One or more errors occurred.
  VTable setup of type MonoDevelop.PackageManagement.ConsoleHostMSBuildNuGetProject failed

**Comment by mrward** [comment]
Thanks for reporting this. I forgot to look into fixing this in the NuGet package extension with VS Mac 7.3.

**Comment by mrward** [comment]
[MonoDevelop.PackageManagement.Extensions 0.12.6](https://github.com/mrward/monodevelop-addins/blob/gh-pages/7.3/MonoDevelop.PackageManagement.Extensions_0.12.6.mpack) should work in VS Mac 7.3.
