### ISSUE TITLE
Xamarin Studio 5.9.2 support

### ISSUE THREAD

**Issue by dhaligas** [mrward/monodevelop-nuget-extensions#3]
Can you update the add in to support XS 5.9.2 and nuget 2.8.5?

**Comment by mrward** [comment]
Version 0.8 of the addin supports Xamarin Studio 5.9.2.

You can download the [MonoDevelop.PackageManagement.Extensions_0.8.mpack]((http://lastexitcode.com/monodevelop-addins/5.0/MonoDevelop.PackageManagement.Extensions_0.8.mpack)) directly from [GitHub](http://lastexitcode.com/monodevelop-addins/5.0/MonoDevelop.PackageManagement.Extensions_0.8.mpack).

I have also created a separate addin repository which you can add to the Xamarin Studio's Add-in Manager:

    http://lastexitcode.com/monodevelop-addins/5.0/main.mrep

Unfortunately the addin seems to fail to build on the main [MonoDevelop addins gallery](http://addins.monodevelop.com/) so I am unable to publish it there currently.

**Comment by dhaligas** [comment]
thanks!
