### ISSUE TITLE
Support Visual Studio 2019 (8.0)

### ISSUE THREAD

**Issue by ravero** [mrward/monodevelop-nuget-extensions#30]
This extension became essential to my workflow by adding core features missing from the Windows version of Visual Studio.

Actually the extension is not published on the Visual Studio 2019 (8.0) feed. Do you plan on support this release, since it's almost launched (2nd April)?

Regards

**Comment by mrward** [comment]
Yes I am planning to update the extension to work with VS Mac 8.0 and publish it. Just not looked at it yet.

**Comment by ravero** [comment]
Tell me if there's any way I could help.

**Comment by mrward** [comment]
The NuGet extensions addin for VS Mac 8.0 has been published:

http://addins.monodevelop.com/Project/Index/121

**Comment by ravero** [comment]
Thanks for the heads up Matt!
