### ISSUE TITLE
Support for Visual Studio for Mac 8.0

### ISSUE THREAD

**Issue by jzeferino** [mrward/monodevelop-nuget-extensions#31]
Any plans for the new VS4Mac release? Just updated to version 8 and Nuget Package Management is indispensable.

**Comment by mrward** [comment]
It is already available for Visual Studio for Mac 8.0 - http://addins.monodevelop.com/Project/Index/121

https://github.com/mrward/monodevelop-nuget-extensions/issues/30

**Comment by jzeferino** [comment]
Sorry for the duplicate, but didn't found it when checking for updates. Thank you.
