### ISSUE TITLE
Could not load file or assembly 'NuGet.Resolver, Version=5.2.0.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

### ISSUE THREAD

**Issue by vijayneophyte** [mrward/monodevelop-nuget-extensions#34]
Iam getting this issue while trying to install package

**Comment by mrward** [comment]
Would you be able to provide more information?

 - What VS Mac version are you using?
 - What version of the NuGet extensions addin are you using?

**Comment by vijayneophyte** [comment]
Thanks for quick reply. 

=== Visual Studio Community 2019 for Mac ===

Version 8.3.10 (build 2)
Installation UUID: 0276a819-3b05-4a1c-a69a-efd9af11314b
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Version: 3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

A valid Xcode installation was not found at the configured location: '/Applications/Xcode.app'

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin Designer ===

Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:22 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:42 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803100002
Git revision: add3a4998a5cb5b081e0404e1fe13acfecb7801d
Build date: 2019-11-20 13:35:15+00
Build branch: release-8.3
Xamarin extensions: 79c69708816813b498283eeda7bcb4d464433a04

=== Operating System ===

Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
    root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

NuGet Package Management Extensions 0.20

**Comment by mrward** [comment]
Thanks for letting me know. It seems that I updated the NuGet version in VS Mac 8.3 to NuGet 5.3 but did not update the NuGet extensions addin.

I see the following error when opening the NuGet Package Console window:

`Could not load type of field 'NuGetConsole.Host.PowerShell.InstalledPackageEnumerator+<OrderPackagesForPackagesConfigAsync>d__9:<packagesToSort>5__3' (10) due to: Could not load file or assembly 'NuGet.Resolver, Version=5.2.0.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

The NuGet extensions addin was updated to work with the 8.3 previews but that was before the NuGet version was updated in VS Mac.

**Comment by mrward** [comment]
Should be fixed in version 0.21 which has been publised to the main monodevelop/VS Mac gallery.

**Comment by dwildcash** [comment]
Hi,

Iam running latest visual studio Visual Studio 2019 for Mac version 8.5.3 
Nuget 8.5.3
latest nuget extension 0.21

When I try to Install-Package I got this

M> Install-Package Microsoft.Owin.Security.OpenIdConnect
Install-Package : Could not load file or assembly 'NuGet.Resolver, Version=5.3.0.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
At line:1 char:1
+ Install-Package Microsoft.Owin.Security.OpenIdConnect
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.0447359

**Comment by mrward** [comment]
@dwildcash Published version 0.21.1 which works with VS Mac 8.5.

https://addins.monodevelop.com/Project/Index/121
