### ISSUE TITLE
Update-Database command not working on latest Visual Studio for mac

### ISSUE THREAD

**Issue by MuhammadAliYousaf** [mrward/monodevelop-nuget-extensions#45]
Getting following error while running the command `Update-Database`
`Update-Database: The following exception occurred while retrieving member "IsPathRooted": "GenericArguments[0], 'System.ReadOnlySpan`1[System.Char]', on 'System.Func`2[T,TResult]' violates the constraint of type 'T'."`

Using the latest version i.e. 0.33
Visual Studio Mac version is 17.5 Preview (17.5 build 437).

**Comment by mrward** [comment]
Looks like it is related to VS Mac 17.5 now running on .NET 7. Update-Database works fine in VS Mac 17.4, which runs on .NET 6. Same NuGet extensions addin version installed.

**Comment by mrward** [comment]
I have a fix for this but it will need to wait for Visual Studio for Mac 17.5 preview 2. Preview 1 seems to use Microsoft.Extensions.ObjectPool 6.0.0 which is not compatible with PowerShell 7.3. VS Mac preview 2 uses Microsoft.Extensions.ObjectPool 7.0.0.

**Comment by mrward** [comment]
Visual Studio for Mac 17.5 preview 2 was released yesterday. NuGet extensions 0.34 should be available from the Extensions Manager at some point. Also available to download directly:

https://github.com/mrward/monodevelop-addins/raw/gh-pages/17.5/MonoDevelop.PackageManagement.Extensions.0.34.mpack
