### ISSUE TITLE
Support for Studio 5.10 and Nuget 2.8.7

### ISSUE THREAD

**Issue by dhaligas** [mrward/monodevelop-nuget-extensions#7]
We cannot use this addin with Studio 5.10 b/c is uses Nuget 2.8.7.  

can you update this to support it?

**Comment by mrward** [comment]
Version 0.10.1 of the NuGet extensions addin should work with Xamarin Studio 5.10. It should be on the [alpha addin repository[(https://github.com/mrward/monodevelop-nuget-extensions#installation).

Alternatively you can download the [.mpack](https://github.com/mrward/monodevelop-addins/blob/gh-pages/5.0/MonoDevelop.PackageManagement.Extensions_0.10.1.mpack) and install it using the Install  from file button on the Addin Manager dialog.
